#include "pch.h"
#include "app/infrastructure/exporters/HtmlReportExporter.h"
#include <string>
#include <vector>

BOOL HtmlReportExporter::Export(const DataTable& table, const CString& strFilePath, CString& strError)
{
    std::wstring html = BuildHtml(table);
    return WriteHtmlFile(strFilePath, html, strError);
}

BOOL HtmlReportExporter::WriteHtmlFile(const CString& strPath, const std::wstring& content, CString& strError) const
{
    int nUtf8Len = WideCharToMultiByte(CP_UTF8, 0, content.c_str(), -1, nullptr, 0, nullptr, nullptr);
    if (nUtf8Len <= 0)
    {
        strError = L"UTF-8 변환에 실패했습니다.";
        return FALSE;
    }

    std::vector<char> arrUtf8(nUtf8Len);
    WideCharToMultiByte(CP_UTF8, 0, content.c_str(), -1, arrUtf8.data(), nUtf8Len, nullptr, nullptr);

    HANDLE hFile = CreateFileW(strPath, GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, nullptr);
    if (hFile == INVALID_HANDLE_VALUE)
    {
        strError.Format(L"파일을 생성할 수 없습니다: %s", (LPCWSTR)strPath);
        return FALSE;
    }

    DWORD dwWritten = 0;
    int nDataLen = nUtf8Len - 1;
    WriteFile(hFile, arrUtf8.data(), static_cast<DWORD>(nDataLen), &dwWritten, nullptr);
    CloseHandle(hFile);
    return TRUE;
}

std::wstring HtmlReportExporter::BuildHtml(const DataTable& table) const
{
    CString strSourceName = table.GetSourceName();
    CString strTimestamp  = GetCurrentTimestamp();
    wchar_t szRows[16]    = {};
    wchar_t szCols[16]    = {};
    _itow_s(table.GetRowCount(),    szRows, 16, 10);
    _itow_s(table.GetColumnCount(), szCols, 16, 10);

    std::wstring html;
    html.reserve(512 * 1024);

    html +=
        L"<!DOCTYPE html>"
        L"<html lang=\"ko\">"
        L"<head>"
        L"<meta charset=\"UTF-8\">"
        L"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">"
        L"<title>SageNexus Report</title>"
        L"<style>"
        L"*{box-sizing:border-box;margin:0;padding:0}"
        L"body{font-family:'Segoe UI',system-ui,sans-serif;background:#f4f4f8;padding:32px;color:#222}"
        L".header{background:linear-gradient(135deg,#1a1a2e,#2d2d44);color:#fff;padding:28px 32px;border-radius:10px;margin-bottom:24px}"
        L".header-title{font-size:20px;font-weight:600;margin-bottom:8px}"
        L".header-meta{font-size:13px;opacity:.65}"
        L".header-meta span{margin-right:20px}"
        L".table-wrap{background:#fff;border-radius:10px;overflow:auto;box-shadow:0 1px 6px rgba(0,0,0,.07)}"
        L"table{border-collapse:collapse;width:100%;font-size:13px}"
        L"thead tr{background:#2d2d44}"
        L"th{color:#fff;padding:11px 14px;text-align:left;font-weight:500;white-space:nowrap;letter-spacing:.02em}"
        L"td{padding:9px 14px;border-bottom:1px solid #f0f0f0;white-space:nowrap}"
        L"tbody tr:last-child td{border-bottom:none}"
        L"tbody tr:hover td{background:#f7f7ff}"
        L".footer{margin-top:20px;text-align:right;font-size:12px;color:#aaa}"
        L"</style>"
        L"</head>"
        L"<body>"
        L"<div class=\"header\">"
        L"<div class=\"header-title\">";

    html += EscapeHtml(strSourceName);
    html +=
        L"</div>"
        L"<div class=\"header-meta\">"
        L"<span>&#128200; ";
    html += szRows;
    html += L"행</span><span>&#9783; ";
    html += szCols;
    html += L"열</span><span>&#128337; ";
    html += (LPCWSTR)strTimestamp;
    html +=
        L"</span>"
        L"</div>"
        L"</div>"
        L"<div class=\"table-wrap\">"
        L"<table>"
        L"<thead><tr>";
    html += BuildHeaderRow(table);
    html +=
        L"</tr></thead>"
        L"<tbody>";
    html += BuildDataRows(table);
    html +=
        L"</tbody>"
        L"</table>"
        L"</div>"
        L"<div class=\"footer\">Generated by SageNexus</div>"
        L"</body>"
        L"</html>";

    return html;
}

std::wstring HtmlReportExporter::BuildHeaderRow(const DataTable& table) const
{
    std::wstring html;
    for (int i = 0; i < table.GetColumnCount(); ++i)
    {
        const DataColumn& col = table.GetColumn(i);
        CString strHeader = col.m_strDisplayNameKo.IsEmpty() ? col.m_strInternalName : col.m_strDisplayNameKo;
        html += L"<th>";
        html += EscapeHtml(strHeader);
        html += L"</th>";
    }
    return html;
}

std::wstring HtmlReportExporter::BuildDataRows(const DataTable& table) const
{
    std::wstring html;
    for (int r = 0; r < table.GetRowCount(); ++r)
    {
        const DataRow& row = table.GetRow(r);
        html += L"<tr>";
        int nCellCount = __min((int)row.m_arrCells.size(), table.GetColumnCount());
        for (int c = 0; c < nCellCount; ++c)
        {
            html += L"<td>";
            html += EscapeHtml(row.m_arrCells[c]);
            html += L"</td>";
        }
        for (int c = (int)row.m_arrCells.size(); c < table.GetColumnCount(); ++c)
            html += L"<td></td>";
        html += L"</tr>";
    }
    return html;
}

std::wstring HtmlReportExporter::EscapeHtml(const CString& str) const
{
    std::wstring result;
    result.reserve(str.GetLength());
    for (int i = 0; i < str.GetLength(); ++i)
    {
        wchar_t ch = str[i];
        switch (ch)
        {
        case L'&':  result += L"&amp;";  break;
        case L'<':  result += L"&lt;";   break;
        case L'>':  result += L"&gt;";   break;
        case L'"':  result += L"&quot;"; break;
        case L'\'': result += L"&#39;";  break;
        default:    result += ch;        break;
        }
    }
    return result;
}

CString HtmlReportExporter::GetCurrentTimestamp() const
{
    SYSTEMTIME st = {};
    GetLocalTime(&st);
    CString strTs;
    strTs.Format(L"%04d-%02d-%02d %02d:%02d",
        st.wYear, st.wMonth, st.wDay,
        st.wHour, st.wMinute);
    return strTs;
}
